version: "3.8"
services:

  goprx:
    build:
      dockerfile: ./dockerfile.yaml
      context: .
    command: >
      - --record
      - from=to
    ports:
      - "80:80"
    restart: unless-stopped
