version: "3.8"
services:
  #goprx:
    #image:
      #build: ./dockerfile.yaml
      #context: ./
    #ports:
      #  - "80:80"
    #volumes:
      #- ./tls.crt:/app/tls.crt
      #  - ./tls.key:/app/tls.key
    #restart: unless-stopped
    #depends_on:
      #       - dragonfly

   dragonfly:
     image: docker.dragonflydb.io/dragonflydb/dragonfly
     ulimits:
       memlock: -1
     ports:
       - ${REDIS_PORT}:${REDIS_PORT}
     command: >
       --bind ${REDIS_ADDR}
       --dir data
       --dbfilename dump
       --requirepass ${REDIS_PASS} 
       --port ${REDIS_PORT}
     volumes:
       - ./data:/data
     restart: unless-stopped
volumes:
   dragonflydata:
