version: "3.8"
services:
  # goprx:
  #   image:
  #     build: ./dockerfile.yaml
  #     context: ./
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./tls.crt:/app/tls.crt
  #     - ./tls.key:/app/tls.key
  #   restart: unless-stopped
  #   depends_on:
  #     - dragonfly

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: >
      --bind localhost
      --dir data
      --dbfilename dump
      --requirepass ${REDIS_PASSWORD} 
      --port ${REDIS_PORT}
    volumes:
      - ./data:/data
    restart: unless-stopped
volumes:
  dragonflydata: