---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ application.name }}
spec:
  replicas: {{ application.replicas }}
  selector:
    matchLabels:
      app: {{ application.name }}
  template:
    metadata:
      labels:
        app: {{ application.name }}
    spec:
      {{- if application.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml application.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ application.name }}
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}"
          command: ["./main"]
          env:
            - name: JWT_SECRET
              value: {{ application.JWT_SECRET }}
            - name: NAMESPACE
              value: {{ applicaiton.name }}
            - name: PRX_KUBE_CONFIG
              value: {{ applicaiton.PRX_KUBE_CONFIG }}
          args: {{ toJson application.args }}
          ports:
            - containerPort: 80
          {{- if application.resources }}
          resources:
            {{- toYaml application.resources | nindent 12 }}
          {{- end }}