---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ application.name }}
spec:
  tls:
    - hosts:
        - {{ application.host }}
      secretName: {{ application.secretName }}
  rules:
    - host: {{ application.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ application.name }}
                port:
                  number: 443