apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
spec:
  ingressClassName: nginx   
  tls:
    - hosts:
        - {{ .Values.application.host }}
      secretName: {{ .Values.application.secretName }}
  rules:
    - host: {{ .Values.application.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.application.name }}-grpc"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx   
  tls:
    - hosts:
        - rpc.{{ .Values.application.host }}
      secretName: {{ .Values.application.secretName }}
  rules:
    - host: rpc.{{ .Values.application.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  number: 50051
                  name: grpc