apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
spec:
  tls:
    - hosts:
        - {{ .Values.application.host }}
      secretName: {{ .Values.application.secretName }}
  rules:
    - host: {{ .Values.application.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.application.name }}-grpc"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"  
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
spec:
  rules:
    - host: rpc.{{ .Values.application.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  name: grpc
# doks
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#     nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: www.example.com
#       http:
#         paths:
#           - pathType: Prefix
#             backend:
#               service:
#                 name: exampleService
#                 port:
#                   number: 80
#             path: /
#   # This section is only required if TLS is to be enabled for the Ingress
#   tls:
#     - hosts:
#       - www.example.com
#       secretName: example-tls