{{- range .Values.applications }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- end }}