
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.application.name }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.application.name }}"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: grpc