
---
apiVersion: v1
kind: Service
metadata:
  name: {{ application.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ application.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80