// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/reverse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cert          string                 `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"` // base64
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`   // base64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_proto_reverse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_reverse_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ProxyRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ProxyRequest) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *ProxyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_reverse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_reverse_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_reverse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_reverse_proto_rawDescGZIP(), []int{2}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ProxyRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_reverse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_reverse_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetRecords() []*ProxyRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type ProxyRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRecord) Reset() {
	*x = ProxyRecord{}
	mi := &file_proto_reverse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRecord) ProtoMessage() {}

func (x *ProxyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRecord.ProtoReflect.Descriptor instead.
func (*ProxyRecord) Descriptor() ([]byte, []int) {
	return file_proto_reverse_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyRecord) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ProxyRecord) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_reverse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_reverse_proto_rawDescGZIP(), []int{5}
}

var File_proto_reverse_proto protoreflect.FileDescriptor

const file_proto_reverse_proto_rawDesc = "" +
	"\n" +
	"\x13proto/reverse.proto\x12\x03prx\"X\n" +
	"\fProxyRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"\r\n" +
	"\vListRequest\":\n" +
	"\fListResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.prx.ProxyRecordR\arecords\"1\n" +
	"\vProxyRecord\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\a\n" +
	"\x05Empty2\xaf\x01\n" +
	"\aReverse\x12$\n" +
	"\x03Add\x12\x11.prx.ProxyRequest\x1a\n" +
	".prx.Empty\x12'\n" +
	"\x06Update\x12\x11.prx.ProxyRequest\x1a\n" +
	".prx.Empty\x12(\n" +
	"\x06Delete\x12\x12.prx.DeleteRequest\x1a\n" +
	".prx.Empty\x12+\n" +
	"\x04List\x12\x10.prx.ListRequest\x1a\x11.prx.ListResponseB\x10Z\x0einternal/pb;pbb\x06proto3"

var (
	file_proto_reverse_proto_rawDescOnce sync.Once
	file_proto_reverse_proto_rawDescData []byte
)

func file_proto_reverse_proto_rawDescGZIP() []byte {
	file_proto_reverse_proto_rawDescOnce.Do(func() {
		file_proto_reverse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reverse_proto_rawDesc), len(file_proto_reverse_proto_rawDesc)))
	})
	return file_proto_reverse_proto_rawDescData
}

var file_proto_reverse_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_reverse_proto_goTypes = []any{
	(*ProxyRequest)(nil),  // 0: prx.ProxyRequest
	(*DeleteRequest)(nil), // 1: prx.DeleteRequest
	(*ListRequest)(nil),   // 2: prx.ListRequest
	(*ListResponse)(nil),  // 3: prx.ListResponse
	(*ProxyRecord)(nil),   // 4: prx.ProxyRecord
	(*Empty)(nil),         // 5: prx.Empty
}
var file_proto_reverse_proto_depIdxs = []int32{
	4, // 0: prx.ListResponse.records:type_name -> prx.ProxyRecord
	0, // 1: prx.Reverse.Add:input_type -> prx.ProxyRequest
	0, // 2: prx.Reverse.Update:input_type -> prx.ProxyRequest
	1, // 3: prx.Reverse.Delete:input_type -> prx.DeleteRequest
	2, // 4: prx.Reverse.List:input_type -> prx.ListRequest
	5, // 5: prx.Reverse.Add:output_type -> prx.Empty
	5, // 6: prx.Reverse.Update:output_type -> prx.Empty
	5, // 7: prx.Reverse.Delete:output_type -> prx.Empty
	3, // 8: prx.Reverse.List:output_type -> prx.ListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_reverse_proto_init() }
func file_proto_reverse_proto_init() {
	if File_proto_reverse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reverse_proto_rawDesc), len(file_proto_reverse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reverse_proto_goTypes,
		DependencyIndexes: file_proto_reverse_proto_depIdxs,
		MessageInfos:      file_proto_reverse_proto_msgTypes,
	}.Build()
	File_proto_reverse_proto = out.File
	file_proto_reverse_proto_goTypes = nil
	file_proto_reverse_proto_depIdxs = nil
}
