global:
  image:
    repository: ghcr.io/typeterrors/go_proxy
    tag: latest  # This will be overridden by the Helm command

application:
  name: application name
  host: application's FQDN
  TLS_CRT: ""
  TLS_KEY: ""
  secretName: application's FQDN secret name
  replicas: 2
  imagePullSecrets: <your-image-pull-secret>
  JWT_SECRET: "your-secret-value"
  PRX_KUBE_CONFIG: "<new users kube config for application>" # edit the shell secript cluster-service-account.yaml to create the service account with the proper permissions
  image:
    repository: ghcr.io/typeterrors/go_proxy
    # tag: "specific-tag"  # Optional per-application override
