global:
  image:
    repository: ghcr.io/<example-user>/<example-image>
    tag: "latest"  # This will be overridden by the Helm command

application:
    name: example-name
    host: example.com
    secretName: example.io-secret
    replicas: 1
    args:
        - '--record'
        - 'FROM=TO'

