// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proxy.proto

package prx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNewProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cert          string                 `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNewProxyRequest) Reset() {
	*x = AddNewProxyRequest{}
	mi := &file_proto_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNewProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewProxyRequest) ProtoMessage() {}

func (x *AddNewProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewProxyRequest.ProtoReflect.Descriptor instead.
func (*AddNewProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *AddNewProxyRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AddNewProxyRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AddNewProxyRequest) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *AddNewProxyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyRequest) Reset() {
	*x = DeleteProxyRequest{}
	mi := &file_proto_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyRequest) ProtoMessage() {}

func (x *DeleteProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyRequest.ProtoReflect.Descriptor instead.
func (*DeleteProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteProxyRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type PatchProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cert          string                 `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchProxyRequest) Reset() {
	*x = PatchProxyRequest{}
	mi := &file_proto_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchProxyRequest) ProtoMessage() {}

func (x *PatchProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchProxyRequest.ProtoReflect.Descriptor instead.
func (*PatchProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *PatchProxyRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PatchProxyRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PatchProxyRequest) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *PatchProxyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRedirectionRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedirectionRecordsRequest) Reset() {
	*x = GetRedirectionRecordsRequest{}
	mi := &file_proto_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedirectionRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedirectionRecordsRequest) ProtoMessage() {}

func (x *GetRedirectionRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedirectionRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetRedirectionRecordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{3}
}

type RedirectionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectionRecord) Reset() {
	*x = RedirectionRecord{}
	mi := &file_proto_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectionRecord) ProtoMessage() {}

func (x *RedirectionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectionRecord.ProtoReflect.Descriptor instead.
func (*RedirectionRecord) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *RedirectionRecord) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RedirectionRecord) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetRedirectionRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RedirectionRecord   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedirectionRecordsResponse) Reset() {
	*x = GetRedirectionRecordsResponse{}
	mi := &file_proto_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedirectionRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedirectionRecordsResponse) ProtoMessage() {}

func (x *GetRedirectionRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedirectionRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetRedirectionRecordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *GetRedirectionRecordsResponse) GetRecords() []*RedirectionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_proxy_proto protoreflect.FileDescriptor

const file_proto_proxy_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proxy.proto\x12\x03prx\"^\n" +
	"\x12AddNewProxyRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"(\n" +
	"\x12DeleteProxyRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"]\n" +
	"\x11PatchProxyRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"\x1e\n" +
	"\x1cGetRedirectionRecordsRequest\"7\n" +
	"\x11RedirectionRecord\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"Q\n" +
	"\x1dGetRedirectionRecordsResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.prx.RedirectionRecordR\arecords\"\x0f\n" +
	"\rHealthRequest\"V\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\":\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc4\x02\n" +
	"\fProxyService\x125\n" +
	"\vAddNewProxy\x12\x17.prx.AddNewProxyRequest\x1a\r.prx.Response\x125\n" +
	"\vDeleteProxy\x12\x17.prx.DeleteProxyRequest\x1a\r.prx.Response\x123\n" +
	"\n" +
	"PatchProxy\x12\x16.prx.PatchProxyRequest\x1a\r.prx.Response\x12^\n" +
	"\x15GetRedirectionRecords\x12!.prx.GetRedirectionRecordsRequest\x1a\".prx.GetRedirectionRecordsResponse\x121\n" +
	"\x06Health\x12\x12.prx.HealthRequest\x1a\x13.prx.HealthResponseB\fZ\n" +
	"/proto;prxb\x06proto3"

var (
	file_proto_proxy_proto_rawDescOnce sync.Once
	file_proto_proxy_proto_rawDescData []byte
)

func file_proto_proxy_proto_rawDescGZIP() []byte {
	file_proto_proxy_proto_rawDescOnce.Do(func() {
		file_proto_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proxy_proto_rawDesc), len(file_proto_proxy_proto_rawDesc)))
	})
	return file_proto_proxy_proto_rawDescData
}

var file_proto_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_proxy_proto_goTypes = []any{
	(*AddNewProxyRequest)(nil),            // 0: prx.AddNewProxyRequest
	(*DeleteProxyRequest)(nil),            // 1: prx.DeleteProxyRequest
	(*PatchProxyRequest)(nil),             // 2: prx.PatchProxyRequest
	(*GetRedirectionRecordsRequest)(nil),  // 3: prx.GetRedirectionRecordsRequest
	(*RedirectionRecord)(nil),             // 4: prx.RedirectionRecord
	(*GetRedirectionRecordsResponse)(nil), // 5: prx.GetRedirectionRecordsResponse
	(*HealthRequest)(nil),                 // 6: prx.HealthRequest
	(*HealthResponse)(nil),                // 7: prx.HealthResponse
	(*Response)(nil),                      // 8: prx.Response
}
var file_proto_proxy_proto_depIdxs = []int32{
	4, // 0: prx.GetRedirectionRecordsResponse.records:type_name -> prx.RedirectionRecord
	0, // 1: prx.ProxyService.AddNewProxy:input_type -> prx.AddNewProxyRequest
	1, // 2: prx.ProxyService.DeleteProxy:input_type -> prx.DeleteProxyRequest
	2, // 3: prx.ProxyService.PatchProxy:input_type -> prx.PatchProxyRequest
	3, // 4: prx.ProxyService.GetRedirectionRecords:input_type -> prx.GetRedirectionRecordsRequest
	6, // 5: prx.ProxyService.Health:input_type -> prx.HealthRequest
	8, // 6: prx.ProxyService.AddNewProxy:output_type -> prx.Response
	8, // 7: prx.ProxyService.DeleteProxy:output_type -> prx.Response
	8, // 8: prx.ProxyService.PatchProxy:output_type -> prx.Response
	5, // 9: prx.ProxyService.GetRedirectionRecords:output_type -> prx.GetRedirectionRecordsResponse
	7, // 10: prx.ProxyService.Health:output_type -> prx.HealthResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proxy_proto_init() }
func file_proto_proxy_proto_init() {
	if File_proto_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proxy_proto_rawDesc), len(file_proto_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proxy_proto_goTypes,
		DependencyIndexes: file_proto_proxy_proto_depIdxs,
		MessageInfos:      file_proto_proxy_proto_msgTypes,
	}.Build()
	File_proto_proxy_proto = out.File
	file_proto_proxy_proto_goTypes = nil
	file_proto_proxy_proto_depIdxs = nil
}
