name: TagReleaseBuildPush
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: type-terrors-scale-set
    steps:
      - uses: actions/checkout@v3
      
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Calculate next tag
        id: create_tag
        run: |
          COMMIT_SHA=${{ steps.short-sha.outputs.sha }}
          DATE=$(date +'%Y%m%d')
          UNIX_TIME=$(date +%s)
          HEX_UNIX_TIME=$(printf '%x' $UNIX_TIME)
          echo "tag=v_${COMMIT_SHA}.${HEX_UNIX_TIME}" >> $GITHUB_OUTPUT
          echo "tagname=v_${COMMIT_SHA}.${DATE}" >> $GITHUB_OUTPUT
      - name: Docker login
        id: docker_build
        run : |
          echo "building go_proxy image"
          echo ${{ secrets.GH_RUNNER }} | docker login ghcr.io -u delduked --password-stdin
          ls -a

      - name: Docker build
        id: docker-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: goprx
          tags: ${{ steps.create_tag.outputs.tag }} 
          containerfiles: | 
            ./go_proxy.dockerfile  
     
      - name: Push Docker image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: goprx
          tags: ${{ steps.create_tag.outputs.tag }} 
          registry: ghcr.io/typeterrors
          username: delduked
          password: ${{ secrets.GH_RUNNER }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RUNNER }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }} 
          release_name: ${{ steps.create_tag.outputs.tagname }} 
          draft: false
          prerelease: false
